In [1]:
import pandas as pd

data=pd.read_csv("Project 1/olist_customers_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

                            customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 5 columns]

In [ ]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
None

In [ ]:
data.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [ ]:
print(data.isnull().sum())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [ ]:
print(data["customer_unique_id"].duplicated().sum())

3345

In [ ]:
df.to_csv("Project 1/clean_olist_customers_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/olist_geolocation_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

         geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                               1037       -23.545621       -46.639292
1                               1046       -23.546081       -46.644820
2                               1046       -23.546129       -46.642951
3                               1041       -23.544392       -46.639499
4                               1035       -23.541578       -46.641607
...                              ...              ...              ...
1000158                        99950       -28.068639       -52.010705
1000159                        99900       -27.877125       -52.224882
1000160                        99950       -28.071855       -52.014716
1000161                        99980       -28.388932       -51.846871
1000162                        99950       -28.070104       -52.018658

        geolocation_city geolocation_state
0              sao paulo                SP
1              sao paulo                SP
2              sao paulo                SP
3              sao paulo                SP
4              sao paulo                SP
...                  ...               ...
1000158         tapejara                RS
1000159   getulio vargas                RS
1000160         tapejara                RS
1000161  david canabarro                RS
1000162         tapejara                RS

[1000163 rows x 5 columns]

In [ ]:
print(data.isnull().sum())

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [ ]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB
None

In [ ]:
print(data.shape)

(1000163, 5)

In [ ]:
print(df.duplicated().sum())

261836

In [ ]:
df.to_csv("Project 1/clean_olist_geolocation_dataset.csv",index=False)

In [ ]:
data=pd.read_csv("Project 1/olist_order_items_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

                                order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1
1       00018f77f2f0320c557190d7a144bdd3              1
2       000229ec398224ef6ca0657da4fc703e              1
3       00024acbcdf0a6daa1e931b038114c75              1
4       00042b26cf59d7ce69dfabb4e55b4fd9              1
...                                  ...            ...
112645  fffc94f6ce00a00581880bf54a75a037              1
112646  fffcd46ef2263f404302a634eb57f7eb              1
112647  fffce4705a9662cd70adb13d4a31832d              1
112648  fffe18544ffabc95dfada21779c9644f              1
112649  fffe41c64501cc87c801fd61db3f6244              1

                              product_id                         seller_id  \
0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
...                                  ...                               ...
112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

        shipping_limit_date   price  freight_value
0       2017-09-19 09:45:35   58.90          13.29
1       2017-05-03 11:05:13  239.90          19.93
2       2018-01-18 14:48:30  199.00          17.87
3       2018-08-15 10:10:18   12.99          12.79
4       2017-02-13 13:57:51  199.90          18.14
...                     ...     ...            ...
112645  2018-05-02 04:11:01  299.99          43.41
112646  2018-07-20 04:31:48  350.00          36.53
112647  2017-10-30 17:14:25   99.90          16.95
112648  2017-08-21 00:04:32   55.99           8.72
112649  2018-06-12 17:10:13   43.00          12.79

[112650 rows x 7 columns]

In [ ]:
print(data.shape)

(112650, 7)

In [ ]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
None

In [ ]:
print(data.isnull().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [ ]:
df.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
print(df.nunique())

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

In [ ]:
df.to_csv("Project 1/clean_olist_order_items_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/olist_order_payments_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

                                order_id  payment_sequential payment_type  \
0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
...                                  ...                 ...          ...
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

        payment_installments  payment_value
0                          8          99.33
1                          1          24.39
2                          1          65.71
3                          8         107.78
4                          2         128.45
...                      ...            ...
103881                     1         363.31
103882                     2          96.80
103883                     1          47.77
103884                     5         369.54
103885                     1         191.58

[103886 rows x 5 columns]

In [ ]:
print("--- SHAPE ---")
print(df.shape)

print("\n--- INFO ---")
print(df.info())

print("\n --- MISSING VALUE ---")
print(df.isnull().sum())

print("\n --- DUPLICATES ---")
print(df.duplicated().sum())

print("\n --- UNIQUE VALUES ---")
print(df.nunique())

--- SHAPE ---
(103886, 5)

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
None

 --- MISSING VALUE ---
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

 --- DUPLICATES ---
0

 --- UNIQUE VALUES ---

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [ ]:
df.to_csv("Project 1/clean_olist_order_payments_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/olist_order_reviews_dataset.csv")
df=pd.DataFrame(data)
print(df)

                              review_id                          order_id  \
0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1
...                                 ...                               ...
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

       review_score review_comment_title  \
0                 4                  NaN
1                 5                  NaN
2                 5                  NaN
3                 5                  NaN
4                 5                  NaN
...             ...                  ...
99219             5                  NaN
99220             5                  NaN
99221             5                  NaN
99222             4                  NaN
99223             1                  NaN

                                  review_comment_message review_creation_date  \
0                                                    NaN            1/18/2018
1                                                    NaN            3/10/2018
2                                                    NaN            2/17/2018
3                  Recebi bem antes do prazo estipulado.            4/21/2017
4      Parabéns lojas lannister adorei comprar pela I...             3/1/2018
...                                                  ...                  ...
99219                                                NaN             7/7/2018
99220                                                NaN            12/9/2017
99221  Excelente mochila, entrega super rápida. Super...            3/22/2018
99222                                                NaN             7/1/2018
99223  meu produto chegou e ja tenho que devolver, po...             7/3/2017

      review_answer_timestamp
0                   1/18/2018
1                   3/11/2018
2                   2/18/2018
3                   4/21/2017
4                    3/2/2018
...                       ...
99219               7/14/2018
99220              12/11/2017
99221               3/23/2018
99222                7/2/2018
99223                7/3/2017

[99224 rows x 7 columns]

In [ ]:
print("--- SHAPE ---")
print(df.shape)

print("\n--- INFO ---")
print(df.info())

print("\n --- MISSING VALUE ---")
print(df.isnull().sum())

print("\n --- DUPLICATES ---")
print(df.duplicated().sum())

print("\n --- UNIQUE VALUES ---")
print(df.nunique())

--- SHAPE ---
(99224, 7)

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB
None

 --- MISSING VALUE ---
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

 --- DUPLICATES ---
0

 --- UNIQUE VALUES ---
review_id                  98410
order_id                   98673
review_score                   5
review_comment_title        4516
review_comment_message     36155
review_creation_date         636
review_answer_timestamp      715
dtype: int64

In [ ]:
# fill the missing values 
df['review_comment_title']=df['review_comment_title'].fillna('No Title')
df['review_comment_message']=df['review_comment_title'].fillna('No Title')

In [ ]:
df.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [ ]:
df.to_csv("Project 1/clean_olist_order_reviews_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/olist_orders_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

                               order_id                       customer_id  \
0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
...                                 ...                               ...
99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

      order_status order_purchase_timestamp order_approved_at  \
0        delivered          10/2/2017 10:56   10/2/2017 11:07
1        delivered          7/24/2018 20:41    7/26/2018 3:24
2        delivered            8/8/2018 8:38     8/8/2018 8:55
3        delivered         11/18/2017 19:28  11/18/2017 19:45
4        delivered          2/13/2018 21:18   2/13/2018 22:20
...            ...                      ...               ...
99436    delivered            3/9/2017 9:54     3/9/2017 9:54
99437    delivered           2/6/2018 12:58    2/6/2018 13:10
99438    delivered          8/27/2017 14:46   8/27/2017 15:04
99439    delivered           1/8/2018 21:28    1/8/2018 21:36
99440    delivered           3/8/2018 20:57    3/9/2018 11:20

      order_delivered_carrier_date order_delivered_customer_date  \
0                  10/4/2017 19:55              10/10/2017 21:25
1                  7/26/2018 14:31                8/7/2018 15:27
2                   8/8/2018 13:50               8/17/2018 18:06
3                 11/22/2017 13:39                12/2/2017 0:28
4                  2/14/2018 19:46               2/16/2018 18:17
...                            ...                           ...
99436              3/10/2017 11:18               3/17/2017 15:08
99437               2/7/2018 23:22               2/28/2018 17:37
99438              8/28/2017 20:52               9/21/2017 11:24
99439              1/12/2018 15:35               1/25/2018 23:32
99440               3/9/2018 22:11               3/16/2018 13:08

      order_estimated_delivery_date
0                   10/18/2017 0:00
1                    8/13/2018 0:00
2                     9/4/2018 0:00
3                   12/15/2017 0:00
4                    2/26/2018 0:00
...                             ...
99436                3/28/2017 0:00
99437                 3/2/2018 0:00
99438                9/27/2017 0:00
99439                2/15/2018 0:00
99440                 4/3/2018 0:00

[99441 rows x 8 columns]

In [ ]:
print("--- SHAPE ---")
print(df.shape)

print("\n--- INFO ---")
print(df.info())

print("\n --- MISSING VALUE ---")
print(df.isnull().sum())

print("\n --- DUPLICATES ---")
print(df.duplicated().sum())

print("\n --- UNIQUE VALUES ---")
print(df.nunique())

--- SHAPE ---
(99441, 8)

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None

 --- MISSING VALUE ---
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

 --- DUPLICATES ---
0

 --- UNIQUE VALUES ---
order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         88789
order_approved_at                50462
order_delivered_carrier_date     61544
order_delivered_customer_date    75649
order_estimated_delivery_date      459
dtype: int64

In [ ]:
df=df.drop_duplicates(subset=['order_id'])

In [ ]:
df.to_csv("Project 1/clean_olist_order_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/olist_products_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

                             product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
0                     40.0                       287.0                 1.0
1                     44.0                       276.0                 1.0
2                     46.0                       250.0                 1.0
3                     27.0                       261.0                 1.0
4                     37.0                       402.0                 4.0
...                    ...                         ...                 ...
32946                 45.0                        67.0                 2.0
32947                 41.0                       971.0                 1.0
32948                 50.0                       799.0                 1.0
32949                 60.0                       156.0                 2.0
32950                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0
1                1000.0               30.0               18.0
2                 154.0               18.0                9.0
3                 371.0               26.0                4.0
4                 625.0               20.0               17.0
...                 ...                ...                ...
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
0                  14.0
1                  20.0
2                  15.0
3                  26.0
4                  13.0
...                 ...
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0

[32951 rows x 9 columns]

In [ ]:
print("--- SHAPE ---")
print(df.shape)

print("\n--- INFO ---")
print(df.info())

print("\n --- MISSING VALUE ---")
print(df.isnull().sum())

print("\n --- DUPLICATES ---")
print(df.duplicated().sum())

print("\n --- UNIQUE VALUES ---")
print(df.nunique())

--- SHAPE ---
(32951, 9)

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
None

 --- MISSING VALUE ---
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

 --- DUPLICATES ---
0

 --- UNIQUE VALUES ---
product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

In [ ]:
# 1. fill the missing value og product_category_name
df['product_category_name'] = df['product_category_name'].fillna('Unknown')

# 2. fill the missing value of metadata
df['product_name_lenght'] = df['product_name_lenght'].fillna(0)
df['product_description_lenght'] = df['product_description_lenght'].fillna(0)
df['product_photos_qty'] = df['product_photos_qty'].fillna(0)

# 3. fill the missing value of product weight,length,height and width
dim_cols = ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
for col in dim_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
print(df.isnull().sum())

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [ ]:
df.to_csv("Project 1/clean_olist_products_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/olist_sellers_dataset.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

                             seller_id  seller_zip_code_prefix  \
0     3442f8959a84dea7ee197c632cb2df15                   13023
1     d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2     ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3     c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4     51a04a8a6bdcb23deccc82b0b80742cf                   12914
...                                ...                     ...
3090  98dddbc4601dd4443ca174359b237166                   87111
3091  f8201cab383e484733266d1906e2fdfa                   88137
3092  74871d19219c7d518d0090283e03c137                    4650
3093  e603cf3fec55f8697c9059638d6c8eb5                   96080
3094  9e25199f6ef7e7c347120ff175652c3b                   12051

            seller_city seller_state
0              campinas           SP
1            mogi guacu           SP
2        rio de janeiro           RJ
3             sao paulo           SP
4     braganca paulista           SP
...                 ...          ...
3090            sarandi           PR
3091            palhoca           SC
3092          sao paulo           SP
3093            pelotas           RS
3094            taubate           SP

[3095 rows x 4 columns]

In [ ]:
print("--- SHAPE ---")
print(df.shape)

print("\n--- INFO ---")
print(df.info())

print("\n --- MISSING VALUE ---")
print(df.isnull().sum())

print("\n --- DUPLICATES ---")
print(df.duplicated().sum())

print("\n --- UNIQUE VALUES ---")
print(df.nunique())

--- SHAPE ---
(3095, 4)

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
None

 --- MISSING VALUE ---
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

 --- DUPLICATES ---
0

 --- UNIQUE VALUES ---
seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

In [ ]:
df.to_csv("Project 1/clean_olist_sellers_dataset.csv")

In [ ]:
data=pd.read_csv("Project 1/product_category_name_translation.csv")

In [ ]:
df=pd.DataFrame(data)
print(df)

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [ ]:
print("--- SHAPE ---")
print(df.shape)

print("\n--- INFO ---")
print(df.info())

print("\n --- MISSING VALUE ---")
print(df.isnull().sum())

print("\n --- DUPLICATES ---")
print(df.duplicated().sum())

print("\n --- UNIQUE VALUES ---")
print(df.nunique())

--- SHAPE ---
(71, 2)

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB
None

 --- MISSING VALUE ---
product_category_name            0
product_category_name_english    0
dtype: int64

 --- DUPLICATES ---
0

 --- UNIQUE VALUES ---
product_category_name            71
product_category_name_english    71
dtype: int64

In [ ]:
df.to_csv("Project 1/clean_product_category_name_translation.csv")

In [ ]:
import pandas as pd

# Load the cleaned files 
orders = pd.read_csv("Project 1/clean_olist_order_dataset.csv")
order_items = pd.read_csv("Project 1/olist_order_items_dataset.csv")
products = pd.read_csv("Project 1/clean_olist_products_dataset.csv")
translation = pd.read_csv("Project 1/clean_product_category_name_translation.csv")
payments = pd.read_csv("Project 1/olist_order_payments_dataset.csv")
customers = pd.read_csv("Project 1/clean_olist_customers_dataset.csv")

# 2. Step-by-step merge 
df_merged = orders.merge(order_items, on='order_id', how='left', suffixes=('_orders', '_items'))
df_merged = df_merged.merge(products, on='product_id', how='left', suffixes=('', '_prod'))
df_merged = df_merged.merge(translation, on='product_category_name', how='left', suffixes=('', '_trans'))
df_merged = df_merged.merge(payments, on='order_id', how='left', suffixes=('', '_pay'))
df_merged = df_merged.merge(customers, on='customer_id', how='left', suffixes=('', '_cust'))

print("Merge Complete! Merged Shape:", df_merged.shape)

Merge Complete! Merged Shape: (118434, 35)

## Which product category has the highest revenue

In [ ]:
#category wise total revenue
top_category=(
    df_merged.groupby('product_category_name_english')['payment_value'].sum().sort_values(ascending=False).reset_index()
)

print("Top 5 Revenue Categories:")
print(top_category.head())

Top 5 Revenue Categories:
  product_category_name_english  payment_value
0                bed_bath_table     1712553.67
1                 health_beauty     1657373.12
2         computers_accessories     1585330.45
3               furniture_decor     1430176.39
4                 watches_gifts     1429216.68

## Which month had peak sales

In [ ]:
# Ensure the purchase timestamp in datetime 
df_merged['order_purchase_timestamp'] = pd.to_datetime(df_merged['order_purchase_timestamp'])

# extract year-month
df_merged['year_month'] = df_merged['order_purchase_timestamp'].dt.to_period('M')

# Monthly revenue 
monthly_sales = (
    df_merged.groupby('year_month')['payment_value']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print("Peak Sales Month:")
print(monthly_sales.head(1))

Peak Sales Month:
  year_month  payment_value
0    2017-11     1599444.18

## Which Region Performs Best

In [ ]:
# Customer State-wise revenue
top_regions = (
    df_merged.groupby('customer_state')['payment_value']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

print("Top 5 Performing States:")
print(top_regions.head())

Top 5 Performing States:
  customer_state  payment_value
0             SP     7673188.55
1             RJ     2783724.26
2             MG     2341861.47
3             RS     1152019.17
4             PR     1074614.19

## What is the average order value (AOV) trend

In [ ]:
# Total Revenue per month / Total Distinct Orders per month
aov_trend = (
    df_merged.groupby('year_month')
    .agg(total_revenue=('payment_value', 'sum'), total_orders=('order_id', 'nunique'))
    .reset_index()
)

aov_trend['AOV'] = aov_trend['total_revenue'] / aov_trend['total_orders']

print("Monthly AOV Trend:")
print(aov_trend.head(10))

Monthly AOV Trend:
  year_month  total_revenue  total_orders         AOV
0    2016-09         388.47             4   97.117500
1    2016-10       76120.17           324  234.938796
2    2016-12          19.62             1   19.620000
3    2017-01      189015.66           800  236.269575
4    2017-02      349701.93          1780  196.461758
5    2017-03      544738.23          2682  203.108960
6    2017-04      510891.55          2404  212.517284
7    2017-05      731017.09          3700  197.572186
8    2017-06      608891.38          3245  187.639871
9    2017-07      744599.53          4026  184.947722

## What is the customer review score distribution

In [ ]:
reviews = pd.read_csv("Project 1/olist_order_reviews_dataset.csv")

# Review score distribution (%)
review_dist = (reviews['review_score'].value_counts(normalize=True) * 100).reset_index()
review_dist.columns = ['review_score', 'percentage']

print("Review Score Distribution (%):")
print(review_dist.sort_values(by='review_score', ascending=False))

Review Score Distribution (%):
   review_score  percentage
0             5   57.776344
1             4   19.291704
3             3    8.242965
4             2    3.175643
2             1   11.513344